dm/Controllers/AdminPanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dm.Controllers
{
    public class AdminPanelController : Controller
	{
		[Authorize]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult users_profile()
		{
			return View();
		}
        [Authorize]
        public IActionResult pages_faq()
		{
			return View();
		}
        [Authorize]
        public IActionResult pages_contact()
		{
			return View();
		}
		public IActionResult pages_login()
		{
			return View();
		}
		public IActionResult pages_error_404()
		{
			return View();
		}
	}
}

dm/Controllers/EmployeeController.cs
using dm.Data;
using dm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;

namespace dm.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext applicationDBContext;

        public EmployeeController(ApplicationDbContext applicationDBContext)
        {
            this.applicationDBContext = applicationDBContext;
        }
        [Authorize]
        public IActionResult AddEmployee()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult AddEmployee(Employees employee, IFormFile imgfile)
        {
            if (imgfile != null && imgfile.Length > 0)
            {
                var fileName = Path.GetFileName(imgfile.FileName);
                var random = new Random();
                var randomNumber = random.Next(1, 200);
                var uniqueFileName = randomNumber + fileName;
                var folderPath = Path.Combine(HttpContext.Request.PathBase.Value, "wwwroot/uploads");

                if (!Directory.Exists(folderPath))
                {
                    Directory.CreateDirectory(folderPath);
                }

                string filePath = Path.Combine(folderPath, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    imgfile.CopyTo(stream);
                }

                var dbImagePath = Path.Combine("uploads", uniqueFileName);
                employee.Image = dbImagePath;

                applicationDBContext.Employees.Add(employee);
                applicationDBContext.SaveChanges();
            }

            return RedirectToAction("FetchEmployee");
        }
        [Authorize]
        public IActionResult FetchEmployee()
        {
            return View(applicationDBContext.Employees.ToList());
        }
        [Authorize]
        public IActionResult DeleteEmployee(int id)
        {
            Employees employee = applicationDBContext.Employees.Find(id);
            applicationDBContext.Employees.Remove(employee);
            applicationDBContext.SaveChanges();
            return RedirectToAction("FetchEmployee");
        }

        public IActionResult EditEmployee(int id)
        {
            return View(applicationDBContext.Employees.Find(id));
        }
        [Authorize]
        [HttpPost]
        public IActionResult EditEmployee(Employees employee, IFormFile imgfile)
        {
            if (imgfile != null && imgfile.Length > 0)
            {
                var fileName = Path.GetFileName(imgfile.FileName);
                var random = new Random();
                var randomNumber = random.Next(1, 200);
                var uniqueFileName = randomNumber + fileName;
                var folderPath = Path.Combine(HttpContext.Request.PathBase.Value, "wwwroot/uploads");

                if (!Directory.Exists(folderPath))
                {
                    Directory.CreateDirectory(folderPath);
                }

                string filePath = Path.Combine(folderPath, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    imgfile.CopyTo(stream);
                }

                var dbImagePath = Path.Combine("uploads", uniqueFileName);
                employee.Image = dbImagePath;

                applicationDBContext.Employees.Update(employee);
                applicationDBContext.SaveChanges();
            }

            return RedirectToAction("FetchEmployee");
        }

        [Authorize]
        public IActionResult delete(int id)
        {
            Employees employee = applicationDBContext.Employees.Find(id);
            applicationDBContext.Employees.Remove(employee);
            applicationDBContext.SaveChanges();
            return RedirectToAction("FetchEmployee");
        }
    }
}

dm/Controllers/ServiceController.cs
using Azure;
using dm.Data;
using dm.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dm.Controllers
{
    public class ServiceController : Controller
    {
        private readonly ApplicationDbContext applicationDBContext;

        public ServiceController(ApplicationDbContext applicationDBContext)
        {
            this.applicationDBContext = applicationDBContext;
        }
        [Authorize]
        public IActionResult AddServices()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddServices(Services addService)
        {
            var service = new Services
            {
                Heading = addService.Heading,
                About = addService.About,
                Content = addService.Content
            };
            applicationDBContext.Services.Add(addService);
            applicationDBContext.SaveChanges();
            return View();
        }
        [Authorize]
        public IActionResult FetchServices()
        {
            return View(applicationDBContext.Services.ToList());
        }
        public IActionResult deleteService(int id)
        {
            Services Service = applicationDBContext.Services.Find(id);
            applicationDBContext.Services.Remove(Service);
            applicationDBContext.SaveChanges();
            return RedirectToAction("FetchServices");
        }
        public IActionResult EditServices(int id)
        {

            return View(applicationDBContext.Services.Find(id));
        }
        [Authorize]
        [HttpPost]
        public IActionResult EditServices(Services addService)
        {

            applicationDBContext.Services.Update(addService);
            applicationDBContext.SaveChanges();
            return RedirectToAction("FetchServices");
        }
        [Authorize]
        public IActionResult delete(int id)
        {
            Services addService = applicationDBContext.Services.Find(id);
            applicationDBContext.Services.Remove(addService);
            applicationDBContext.SaveChanges();
            return RedirectToAction("FetchServices");
        }
    }
}

dm/Views/Shared/_Layoutadmin.cshtml
 <link href="~/img/favicon.png" rel="icon">
  <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/css/style.css" rel="stylesheet">
 



<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="/img/logo.png" alt="">
        <span class="d-none d-lg-block">AdminPanel</span>
            @Html.Partial("_LoginPartial")
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->



        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">

            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Kevin Anderson</h6>
              <span>Admin</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>


            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->
   <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " asp-controller="AdminPanel" asp-action="index">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Employee</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a asp-controller="Employee" asp-action="AddEmployee">
              <i class="bi bi-circle"></i><span>Add Employee</span>
            </a>
          </li>
          <li>
            <a asp-action="FetchEmployee" asp-controller="Employee">
              <i class="bi bi-circle"></i><span>Total Employees</span>
            </a>
          </li>




        </ul>
      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" >
          <i class="bi bi-journal-text"></i><span>Services</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
                    <a asp-controller="Service" asp-action="AddServices">
              <i class="bi bi-circle"></i><span>Add Services</span>
            </a>
          </li>
          <li>
                    <a asp-controller="Service" asp-action="FetchServices">
              <i class="bi bi-circle"></i><span>All Services</span>
            </a>
          </li>

        </ul>
      </li>
@* 
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-layout-text-window-reverse"></i><span>Users</span><i class="bi bi-chevron-down ms-auto"></i>
        </a> *@
       @*  <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav"> *@
          @* <li>
            <a asp-controller="Employee" asp-action="FetchEmployee">
              <i class="bi bi-circle"></i><span>All Users</span>
            </a>
          </li>
          <li>
            <a asp-controller="Employee" asp-action="AddEmployee">
              <i class="bi bi-circle"></i><span>Add User</span>
            </a>
          </li> *@
        @* </ul>
        </li>*@<!-- End Tables Nav -->



      <li class="nav-item">
        <a class="nav-link collapsed"  href="pages-contact.html">
          <i class="bi bi-menu-button-wide"></i><span>Contact</span>
        </a>

  </aside><!-- End Sidebar-->
  
        @RenderBody()


        <!-- ======= Footer ======= -->
       <footer id="footer" class="footer">


  </footer>

  <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/vendor/chart.js/chart.umd.js"></script>
  <script src="~/vendor/echarts/echarts.min.js"></script>
  <script src="~/vendor/quill/quill.min.js"></script>
  <script src="~/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/js/main.js"></script>